package main

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// getNetworksAllNetworksNetworkType includes the requested fields of the GraphQL type NetworkType.
type getNetworksAllNetworksNetworkType struct {
	Name string `json:"name"`
}

// getNetworksResponse is returned by getNetworks on success.
type getNetworksResponse struct {
	AllNetworks []getNetworksAllNetworksNetworkType `json:"allNetworks"`
}

func getNetworks(
	ctx context.Context,
	client graphql.Client,
) (*getNetworksResponse, error) {
	var err error

	var retval getNetworksResponse
	err = client.MakeRequest(
		ctx,
		"getNetworks",
		`
query getNetworks {
	allNetworks {
		name
	}
}
`,
		&retval,
		nil,
	)
	return &retval, err
}
